# Generated by Django 4.2.3 on 2023-07-16 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0004_alter_appointments_additional_drink_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timesched", old_name="name", new_name="time",
        ),
    ]
