# Generated by Django 4.2.3 on 2023-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0006_rename_customer_appointments_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage",
            name="category",
            field=models.CharField(
                choices=[
                    ("Whisky & Whiskey", "Whisky & Whiskey"),
                    ("Gin & Gon + Tonic", "Gin & Gon + Tonic"),
                    ("Cocktail", "Cocktail"),
                    ("Beer", "Beer"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
