# Generated by Django 4.2.3 on 2023-07-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0007_alter_beverage_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
