# Generated by Django 4.2.3 on 2023-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0008_alter_beverage_description"),
    ]

    operations = [
        migrations.RenameModel(old_name="appointments", new_name="appointment",),
        migrations.AlterField(
            model_name="beverage",
            name="category",
            field=models.CharField(
                choices=[
                    ("Whisky & Whiskey", "Whisky & Whiskey"),
                    ("Gin & Gon + Tonic", "Gin & Gon + Tonic"),
                    ("Cocktail", "Cocktail"),
                    ("Beer", "Beer"),
                    ("Coffee & Tea", "Coffee & Tea"),
                    ("Soda", "Soda"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
