# Generated by Django 4.2.3 on 2023-07-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0009_rename_appointments_appointment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beverage",
            name="category",
            field=models.CharField(
                choices=[
                    ("Whisky & Whiskey", "Whisky & Whiskey"),
                    ("Gin & Gin + Tonic", "Gin & Gin + Tonic"),
                    ("Cocktail", "Cocktail"),
                    ("Beer", "Beer"),
                    ("Coffee & Tea", "Coffee & Tea"),
                    ("Soda", "Soda"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
