# Generated by Django 4.2.3 on 2023-07-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0010_alter_beverage_category"),
    ]

    operations = [
        migrations.RenameModel(old_name="timesched", new_name="timeschedule",),
    ]
