# Generated by Django 4.2.3 on 2023-07-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0016_customer_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="user",),
        migrations.AlterField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(
                blank=True, default="barberian logo.png", null=True, upload_to=""
            ),
        ),
    ]
