# Generated by Django 4.2.3 on 2023-07-25 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0017_remove_customer_user_alter_customer_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="profile_pic",),
    ]
