# Generated by Django 4.2.3 on 2023-07-26 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointmentsystem", "0018_remove_customer_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeschedule",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
