# Generated by Django 4.2.3 on 2023-07-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0019_timeschedule_booked_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeschedule", name="date", field=models.DateField(null=True),
        ),
    ]
