# Generated by Django 4.2.3 on 2023-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0020_timeschedule_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeschedule",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
