# Generated by Django 4.2.3 on 2023-07-27 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0023_appointment_date_alter_appointment_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 28, 9, 46, 45, 222051, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
