# Generated by Django 4.2.3 on 2023-07-27 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0024_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 7, 28, 9, 47, 17, 624290, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
