# Generated by Django 4.2.3 on 2023-07-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0025_alter_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment", name="date", field=models.DateField(),
        ),
    ]
