# Generated by Django 4.2.3 on 2023-07-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0028_alter_appointment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appointment", old_name="date", new_name="day",
        ),
    ]
