# Generated by Django 4.2.3 on 2023-07-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0031_alter_appointmentnew_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnew",
            name="service",
            field=models.CharField(
                choices=[
                    ("Doctor care", "Doctor care"),
                    ("Nursing care", "Nursing care"),
                    ("Medical social services", "Medical social services"),
                    (
                        "Homemaker or basic assistance care",
                        "Homemaker or basic assistance care",
                    ),
                ],
                default="Doctor care",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="appointmentnew",
            name="time",
            field=models.CharField(
                choices=[
                    ("3 PM", "3 PM"),
                    ("3:30 PM", "3:30 PM"),
                    ("4 PM", "4 PM"),
                    ("4:30 PM", "4:30 PM"),
                    ("5 PM", "5 PM"),
                    ("5:30 PM", "5:30 PM"),
                    ("6 PM", "6 PM"),
                    ("6:30 PM", "6:30 PM"),
                    ("7 PM", "7 PM"),
                    ("7:30 PM", "7:30 PM"),
                ],
                default="3 PM",
                max_length=10,
            ),
        ),
    ]
