# Generated by Django 4.2.3 on 2023-07-27 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0032_alter_appointmentnew_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnew",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentsystem.service",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentnew",
            name="time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentsystem.timeschedule",
            ),
        ),
    ]
