# Generated by Django 4.2.3 on 2023-07-27 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0036_alter_appointmentnew_time_ordered"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnew",
            name="time_ordered",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
