# Generated by Django 4.2.3 on 2023-07-27 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0037_alter_appointmentnew_time_ordered"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentnew",
            name="corresponding_drink",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentsystem.complementarydrink",
            ),
        ),
    ]
