# Generated by Django 4.2.3 on 2023-07-27 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0038_appointmentnew_corresponding_drink"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentnew",
            name="chosen_barber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentsystem.barber",
            ),
        ),
    ]
