# Generated by Django 4.2.3 on 2023-07-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0040_appointmentnew_additional_drink"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointmentnew", name="additional_drink",),
        migrations.AddField(
            model_name="appointmentnew",
            name="additional_drinks",
            field=models.ManyToManyField(blank=True, to="appointmentsystem.beverage"),
        ),
    ]
