# Generated by Django 4.2.3 on 2023-07-27 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0041_remove_appointmentnew_additional_drink_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointmentnew", name="additional_drinks",),
        migrations.AddField(
            model_name="appointmentnew",
            name="additional_drinks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointmentsystem.beverage",
            ),
        ),
    ]
