# Generated by Django 4.2.3 on 2023-07-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0043_remove_appointmentnew_additional_drinks_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnew",
            name="additional_drinks",
            field=models.ManyToManyField(blank=True, to="appointmentsystem.beverage"),
        ),
    ]
