# Generated by Django 4.2.3 on 2023-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0044_alter_appointmentnew_additional_drinks"),
    ]

    operations = [
        migrations.RemoveField(model_name="appointment", name="additional_drink",),
        migrations.AlterField(
            model_name="appointmentnew",
            name="additional_drinks",
            field=models.ManyToManyField(
                blank=True, null=True, to="appointmentsystem.beverage"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="additional_drink",
            field=models.ManyToManyField(
                blank=True, null=True, to="appointmentsystem.beverage"
            ),
        ),
    ]
