# Generated by Django 4.2.3 on 2023-07-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0045_remove_appointment_additional_drink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="additional_drink",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="appointment_additional_drinks",
                to="appointmentsystem.beverage",
            ),
        ),
    ]
