# Generated by Django 4.2.3 on 2023-07-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointmentsystem", "0047_alter_appointment_additional_drink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentnew",
            name="chosen_barber",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="appointmentsystem.barber",
            ),
        ),
    ]
